In [4]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Users\mgmorenogonz\OneDrive - Université Paris 1 Panthéon-Sorbonne\FTD\deeplearning\climate_tail_risk_project

In [5]:
from src.paths import ROOT, RAW, INTERIM, PROCESSED

print("ROOT:", ROOT)
print("RAW:", RAW)
print("INTERIM:", INTERIM)
print("PROCESSED:", PROCESSED)

ROOT: C:\Users\mgmorenogonz\OneDrive - Université Paris 1 Panthéon-Sorbonne\FTD\deeplearning\climate_tail_risk_project
RAW: C:\Users\mgmorenogonz\OneDrive - Université Paris 1 Panthéon-Sorbonne\FTD\deeplearning\climate_tail_risk_project\data\raw
INTERIM: C:\Users\mgmorenogonz\OneDrive - Université Paris 1 Panthéon-Sorbonne\FTD\deeplearning\climate_tail_risk_project\data\interim
PROCESSED: C:\Users\mgmorenogonz\OneDrive - Université Paris 1 Panthéon-Sorbonne\FTD\deeplearning\climate_tail_risk_project\data\processed

In [8]:
import zipfile
from pathlib import Path

news_folder = RAW / "news"
files = list(news_folder.glob("*.zip"))

print(files)

[WindowsPath('C:/Users/mgmorenogonz/OneDrive - Université Paris 1 Panthéon-Sorbonne/FTD/deeplearning/climate_tail_risk_project/data/raw/news/20171205211500.gkg.csv.zip')]

In [9]:
import zipfile

zip_path = files[0]

with zipfile.ZipFile(zip_path, "r") as z:
    print(z.namelist())

['20171205211500.gkg.csv']

In [10]:
with zipfile.ZipFile(zip_path, "r") as z:
    with z.open(z.namelist()[0]) as f:
        for _ in range(5):
            print(f.readline().decode("utf-8", errors="replace"))

20171205211500-0	20171205211500	1	infiniteunknown.net	http://www.infiniteunknown.net/2008/11/15/vladimir-putin-wanted-to-hang-georgian-president-saakashvili-by-the-balls/			TAX_ETHNICITY;TAX_ETHNICITY_GEORGIAN;TAX_WORLDLANGUAGES;TAX_WORLDLANGUAGES_GEORGIAN;LEADER;TAX_FNCACT;TAX_FNCACT_PRESIDENT;USPEC_POLITICS_GENERAL1;TAX_ETHNICITY_AMERICANS;UNREST_BELLIGERENT;TAX_ETHNICITY_RUSSIAN;TAX_WORLDLANGUAGES_RUSSIAN;TAX_FNCACT_MINISTER;TAX_FNCACT_PRIME_MINISTER;TAX_WORLDLANGUAGES_RUSSIA;TAX_FNCACT_BROKER;CEASEFIRE;TAX_FNCACT_CHIEF;TAX_FNCACT_ADVISER;MEDIA_MSM;TAX_ETHNICITY_FRENCH;TAX_WORLDLANGUAGES_FRENCH;TAX_FNCACT_LEADER;GENERAL_GOVERNMENT;EPU_POLICY;EPU_POLICY_GOVERNMENT;TAX_FNCACT_OFFICIAL;TAX_ETHNICITY_CHECHEN;TAX_WORLDLANGUAGES_CHECHEN;TAX_FNCACT_SEPARATISTS;SEPARATISTS;CRISISLEX_T04_INFRASTRUCTURE;TAX_FNCACT_JOURNALIST;TAX_FNCACT_INTERPRETER;TAX_ETHNICITY_GERMAN;TAX_WORLDLANGUAGES_GERMAN;TAX_FNCACT_LEADERS;CRISISLEX_CRISISLEXREC;TAX_DISEASE;TAX_DISEASE_IMPOTENCE;TAX_WORLDMAMMALS;TAX_WORLDMAMMALS_HUMAN;SELF_IDENTIFIED_HUMAN_RIGHTS;WB_2203_HUMAN_RIGHTS;WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE;UNGP_CRIME_VIOLENCE;EPU_POLICY_POLITICAL;	GENERAL_GOVERNMENT,977;EPU_POLICY_GOVERNMENT,977;TAX_ETHNICITY_GERMAN,2881;TAX_WORLDLANGUAGES_GERMAN,2881;EPU_POLICY_POLITICAL,3670;TAX_WORLDMAMMALS_HUMAN,3381;TAX_FNCACT_LEADERS,3091;TAX_FNCACT_PRIME_MINISTER,471;TAX_ETHNICITY_AMERICANS,204;TAX_ETHNICITY_AMERICANS,1232;TAX_WORLDLANGUAGES_RUSSIA,564;TAX_WORLDLANGUAGES_RUSSIA,737;TAX_WORLDLANGUAGES_RUSSIA,1769;TAX_WORLDLANGUAGES_RUSSIA,3180;TAX_WORLDLANGUAGES_RUSSIA,3260;TAX_WORLDLANGUAGES_RUSSIA,3341;TAX_WORLDLANGUAGES_RUSSIA,3568;TAX_FNCACT_SEPARATISTS,1986;SEPARATISTS,1986;CEASEFIRE,596;CEASEFIRE,3285;CEASEFIRE,3604;TAX_DISEASE_IMPOTENCE,3165;TAX_ETHNICITY_CHECHEN,1974;TAX_WORLDLANGUAGES_CHECHEN,1974;TAX_ETHNICITY_GEORGIAN,47;TAX_WORLDLANGUAGES_GEORGIAN,47;TAX_FNCACT_MINISTER,471;TAX_FNCACT_JOURNALIST,2123;TAX_FNCACT_CHIEF,655;TAX_FNCACT_ADVISER,674;TAX_ETHNICITY_FRENCH,793;TAX_ETHNICITY_FRENCH,1553;TAX_ETHNICITY_FRENCH,2112;TAX_ETHNICITY_FRENCH,2403;TAX_ETHNICITY_FRENCH,3698;TAX_WORLDLANGUAGES_FRENCH,793;TAX_WORLDLANGUAGES_FRENCH,1553;TAX_WORLDLANGUAGES_FRENCH,2112;TAX_WORLDLANGUAGES_FRENCH,2403;TAX_WORLDLANGUAGES_FRENCH,3698;CRISISLEX_T04_INFRASTRUCTURE,2052;CRISISLEX_CRISISLEXREC,3127;SELF_IDENTIFIED_HUMAN_RIGHTS,3388;WB_2203_HUMAN_RIGHTS,3388;WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE,3388;UNGP_CRIME_VIOLENCE,3388;TAX_FNCACT_LEADER,800;TAX_FNCACT_LEADER,2480;TAX_FNCACT_BROKER,584;LEADER,57;LEADER,173;LEADER,254;LEADER,812;LEADER,2413;LEADER,3428;TAX_FNCACT_PRESIDENT,57;TAX_FNCACT_PRESIDENT,173;TAX_FNCACT_PRESIDENT,254;TAX_FNCACT_PRESIDENT,812;TAX_FNCACT_PRESIDENT,2413;TAX_FNCACT_PRESIDENT,3428;USPEC_POLITICS_GENERAL1,57;USPEC_POLITICS_GENERAL1,173;USPEC_POLITICS_GENERAL1,254;USPEC_POLITICS_GENERAL1,812;USPEC_POLITICS_GENERAL1,2413;USPEC_POLITICS_GENERAL1,3428;TAX_FNCACT_INTERPRETER,2194;MEDIA_MSM,717;TAX_ETHNICITY_RUSSIAN,456;TAX_ETHNICITY_RUSSIAN,835;TAX_ETHNICITY_RUSSIAN,1016;TAX_ETHNICITY_RUSSIAN,2612;TAX_ETHNICITY_RUSSIAN,3083;TAX_WORLDLANGUAGES_RUSSIAN,456;TAX_WORLDLANGUAGES_RUSSIAN,835;TAX_WORLDLANGUAGES_RUSSIAN,1016;TAX_WORLDLANGUAGES_RUSSIAN,2612;TAX_WORLDLANGUAGES_RUSSIAN,3083;TAX_FNCACT_OFFICIAL,1827;UNREST_BELLIGERENT,313;	1#Germany#GM#GM#51.5#10.5#GM;4#Moscow, Moskva, Russia#RS#RS48#55.7522#37.6156#-2960561;1#Slovak Republic#LO#LO#48.666667#19.5#LO;1#United States#US#US#39.828175#-98.5795#US;4#Munich, Bayern, Germany#GM#GM02#48.15#11.5833#-1829149;4#Paris, France (General), France#FR#FR00#48.8667#2.33333#-1456928;1#Georgia#GG#GG#42#43.5#GG;4#South Ossetia, Georgia (General), Georgia#GG#GG00#42.3333#44#-2329959;5#Abkhazia, Abkhazia**, Georgia#GG#GG02#42.7908#41.1599#10007258;4#Tbilisi, Georgia (General), Georgia#GG#GG00#41.725#44.7908#-2330077;0#Georgia, , Georgia#GG#GG#42#.5#1#GG;1#Russia#RS#RS#60#100#RS;4#Kremlin, Moskva, Russia#RS#RS48#55.7522#37.6156#-2960561;4#Brussels, Bruxelles-Capitale, Belgium#BE#BE11#50.8333#4.33333#-1955538;1#France#FR#FR#46#2#FR	1#Russia#RS#RS##60#100#RS#564;1#Russia#RS#RS##60#100#RS#737;1#Russia#RS#RS##60#100#RS#1769;1#Russia#RS#RS##60#100#RS#3180;1#Russia#RS#RS##60#100#RS#3260;1#Russia#RS#RS##60#100#RS#3341;1#Russia#RS#RS##60#100#RS#3568;1#Americans#US#US##39.828175#-98.5795#US#204;1#Americans#US#US##39.828175#-98.5795#US#1232;5#Abkhazia, Abkhazia**, Georgia#GG#GG02#16451#42.7908#41.1599#10007258#2687;1#France#FR#FR##46#2#FR#1490;1#France#FR#FR##46#2#FR#3507;4#Kremlin, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#1847;1#French#FR#FR##46#2#FR#793;1#French#FR#FR##46#2#FR#1553;1#French#FR#FR##46#2#FR#2112;1#French#FR#FR##46#2#FR#2403;1#French#FR#FR##46#2#FR#3698;4#South Ossetia, Georgia (General), Georgia#GG#GG00#16523#42.3333#44#-2329959#2667;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#265;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#607;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#870;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#956;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#2450;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#2676;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#2696;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#2791;0#Georgia, , Georgia#GG#GG##42#.5#1#GG#3360;1#German#GM#GM##51.5#10.5#GM#2881;4#Paris, France (General), France#FR#FR00#16282#48.8667#2.33333#-1456928#1482;4#Tbilisi, Georgia (General), Georgia#GG#GG00#16525#41.725#44.7908#-2330077#861;4#Tbilisi, Georgia (General), Georgia#GG#GG00#16525#41.725#44.7908#-2330077#3351;1#Russian#RS#RS##60#100#RS#456;1#Russian#RS#RS##60#100#RS#835;1#Russian#RS#RS##60#100#RS#1016;1#Russian#RS#RS##60#100#RS#2612;1#Russian#RS#RS##60#100#RS#3083;1#United States#US#US##39.828175#-98.5795#US#3449;1#Georgian#GG#GG##42#43.5#GG#47;4#Munich, Bayern, Germany#GM#GM02#16532#48.15#11.5833#-1829149#2850;1#Czechoslovakia#LO#LO##48.666667#19.5#LO#2910;4#Brussels, Bruxelles-Capitale, Belgium#BE#BE11#5850#50.8333#4.33333#-1955538#2075;4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#556;4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#1761;4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#3252;4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#3333;4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522#37.6156#-2960561#3560	jean-david levitte;dmitry astahov;vladimir putin;nicolas sarkozy;adolf hitler	Dmitry Astahov,105;Vladimir Putin,15;Vladimir Putin,137;Vladimir Putin,348;Nicolas Sarkozy,234;Adolf Hitler,2840	united states	United States,3449	-1.44694533762058,2.09003215434084,3.53697749196141,5.62700964630225,18.3279742765273,0.643086816720257,570	4#8#12#0#869;1#0#0#1999#1948;1#0#0#2002#2092;1#0#0#1938#2848	wc:570,c12.1:28,c12.10:34,c12.12:14,c12.13:14,c12.14:8,c12.3:11,c12.4:7,c12.5:15,c12.7:24,c12.8:20,c12.9:22,c13.1:1,c13.11:1,c13.12:1,c14.1:17,c14.10:13,c14.11:31,c14.2:24,c14.3:29,c14.4:8,c14.5:42,c14.6:1,c14.7:7,c14.9:1,c15.105:2,c15.115:1,c15.116:3,c15.120:2,c15.122:1,c15.123:1,c15.124:1,c15.138:1,c15.147:2,c15.148:1,c15.15:1,c15.158:1,c15.164:1,c15.173:3,c15.175:1,c15.176:3,c15.18:1,c15.197:1,c15.201:1,c15.202:1,c15.206:1,c15.212:2,c15.215:2,c15.217:1,c15.219:1,c15.22:1,c15.225:1,c15.226:1,c15.241:1,c15.246:1,c15.251:1,c15.26:2,c15.28:1,c15.3:3,c15.31:1,c15.4:1,c15.43:2,c15.50:1,c15.69:1,c15.79:1,c15.83:2,c15.95:1,c16.100:8,c16.101:3,c16.103:3,c16.105:2,c16.106:21,c16.108:1,c16.109:28,c16.11:6,c16.110:68,c16.111:2,c16.113:3,c16.114:28,c16.115:5,c16.116:9,c16.117:10,c16.118:32,c16.12:49,c16.120:21,c16.121:27,c16.122:2,c16.125:31,c16.126:17,c16.127:36,c16.128:3,c16.129:37,c16.130:9,c16.131:22,c16.132:1,c16.134:50,c16.138:9,c16.139:20,c16.140:10,c16.143:2,c16.145:20,c16.146:30,c16.149:1,c16.150:2,c16.151:3,c16.152:2,c16.153:16,c16.155:3,c16.156:6,c16.157:7,c16.159:33,c16.16:8,c16.161:41,c16.162:9,c16.163:16,c16.164:10,c16.165:3,c16.18:1,c16.19:6,c16.2:23,c16.20:3,c16.21:1,c16.22:7,c16.23:3,c16.24:4,c16.26:49,c16.27:2,c16.28:3,c16.29:1,c16.3:5,c16.30:2,c16.31:21,c16.32:2,c16.33:39,c16.34:4,c16.35:21,c16.36:1,c16.37:40,c16.38:11,c16.39:1,c16.4:33,c16.41:21,c16.43:4,c16.45:28,c16.46:4,c16.47:62,c16.48:9,c16.49:2,c16.5:1,c16.50:1,c16.51:1,c16.52:23,c16.53:3,c16.56:14,c16.57:232,c16.58:42,c16.6:39,c16.60:6,c16.61:1,c16.62:20,c16.63:1,c16.64:10,c16.65:10,c16.66:11,c16.68:13,c16.69:20,c16.7:5,c16.70:18,c16.71:5,c16.72:3,c16.73:2,c16.75:20,c16.76:3,c16.77:2,c16.78:12,c16.79:2,c16.81:1,c16.82:1,c16.84:14,c16.85:2,c16.86:2,c16.87:44,c16.88:60,c16.89:13,c16.90:11,c16.91:11,c16.92:29,c16.93:1,c16.94:31,c16.95:35,c16.96:14,c16.97:1,c16.98:29,c16.99:1,c17.1:103,c17.10:48,c17.11:78,c17.12:11,c17.13:8,c17.14:2,c17.15:19,c17.16:18,c17.17:2,c17.18:5,c17.19:27,c17.2:7,c17.20:6,c17.21:4,c17.22:8,c17.23:5,c17.24:47,c17.25:4,c17.26:1,c17.27:45,c17.28:1,c17.29:13,c17.30:5,c17.31:28,c17.32:17,c17.33:22,c17.34:11,c17.35:7,c17.36:18,c17.37:11,c17.38:6,c17.39:19,c17.4:107,c17.40:8,c17.41:24,c17.42:24,c17.43:22,c17.5:88,c17.6:5,c17.7:64,c17.8:31,c17.9:7,c18.116:1,c18.13:4,c18.139:7,c18.180:15,c18.193:18,c18.206:1,c18.24:3,c18.342:28,c18.345:1,c18.35:2,c2.1:8,c2.10:2,c2.100:1,c2.101:7,c2.102:14,c2.103:1,c2.104:51,c2.106:20,c2.107:1,c2.108:6,c2.109:1,c2.11:4,c2.110:32,c2.111:4,c2.112:5,c2.113:3,c2.114:25,c2.115:8,c2.116:17,c2.119:138,c2.12:21,c2.120:1,c2.121:33,c2.122:26,c2.123:1,c2.124:2,c2.125:15,c2.126:27,c2.127:41,c2.128:9,c2.129:58,c2.130:1,c2.131:4,c2.132:9,c2.133:2,c2.134:1,c2.135:2,c2.136:3,c2.137:1,c2.138:2,c2.139:5,c2.14:40,c2.140:5,c2.141:8,c2.142:8,c2.143:43,c2.144:6,c2.145:1,c2.146:5,c2.147:89,c2.148:55,c2.149:8,c2.15:18,c2.150:3,c2.151:2,c2.152:4,c2.153:19,c2.154:16,c2.155:43,c2.156:22,c2.157:37,c2.158:44,c2.159:3,c2.160:14,c2.162:3,c2.165:1,c2.166:4,c2.167:1,c2.169:5,c2.17:5,c2.170:6,c2.172:1,c2.173:16,c2.174:1,c2.175:1,c2.176:2,c2.177:36,c2.178:1,c2.179:22,c2.18:20,c2.180:20,c2.181:21,c2.183:21,c2.185:106,c2.186:7,c2.187:33,c2.188:5,c2.189:5,c2.191:1,c2.192:9,c2.193:34,c2.194:7,c2.195:39,c2.196:8,c2.197:5,c2.198:48,c2.199:15,c2.2:3,c2.200:4,c2.201:3,c2.202:1,c2.203:37,c2.204:37,c2.205:4,c2.206:4,c2.207:7,c2.209:12,c2.21:2,c2.210:51,c2.211:3,c2.212:1,c2.213:8,c2.214:6,c2.215:1,c2.216:7,c2.217:2,c2.218:1,c2.220:11,c2.221:3,c2.222:1,c2.223:4,c2.225:14,c2.226:6,c2.227:3,c2.228:2,c2.23:4,c2.25:36,c2.26:30,c2.27:30,c2.28:4,c2.30:25,c2.31:24,c2.32:3,c2.33:4,c2.34:28,c2.35:29,c2.36:23,c2.37:28,c2.38:1,c2.39:74,c2.40:2,c2.42:3,c2.44:23,c2.45:45,c2.46:54,c2.47:9,c2.48:8,c2.5:1,c2.50:10,c2.52:37,c2.53:3,c2.54:43,c2.55:3,c2.56:2,c2.57:2,c2.58:8,c2.59:2,c2.6:4,c2.60:6,c2.61:4,c2.62:21,c2.64:19,c2.65:3,c2.66:4,c2.68:3,c2.7:1,c2.70:2,c2.71:3,c2.73:8,c2.74:3,c2.75:75,c2.76:348,c2.77:40,c2.78:69,c2.79:11,c2.80:61,c2.81:5,c2.82:19,c2.83:9,c2.84:1,c2.86:18,c2.87:3,c2.88:8,c2.89:16,c2.9:1,c2.90:5,c2.93:6,c2.95:83,c2.96:1,c2.97:5,c2.98:20,c2.99:14,c25.1:1,c25.2:1,c25.3:1,c25.5:1,c25.7:3,c3.1:37,c3.2:24,c3.4:1,c35.1:4,c35.10:1,c35.11:3,c35.12:3,c35.13:1,c35.14:13,c35.15:4,c35.2:5,c35.20:13,c35.21:2,c35.23:1,c35.24:1,c35.25:1,c35.3:1,c35.31:22,c35.32:18,c35.33:18,c35.4:2,c35.5:2,c35.8:1,c39.12:2,c39.13:2,c39.14:2,c39.17:4,c39.18:3,c39.19:2,c39.2:7,c39.20:1,c39.21:1,c39.28:2,c39.3:18,c39.30:1,c39.32:1,c39.36:3,c39.37:17,c39.38:1,c39.39:5,c39.4:16,c39.40:2,c39.41:8,c39.5:4,c39.9:1,c4.15:1,c4.18:1,c4.2:1,c4.23:20,c40.2:1,c40.4:1,c40.5:3,c40.7:1,c40.8:1,c41.1:9,c5.10:35,c5.11:13,c5.12:70,c5.18:2,c5.19:5,c5.20:2,c5.21:9,c5.22:5,c5.23:10,c5.24:5,c5.25:4,c5.26:6,c5.27:7,c5.28:7,c5.29:11,c5.3:1,c5.30:55,c5.31:3,c5.32:4,c5.33:1,c5.34:9,c5.35:10,c5.36:21,c5.37:25,c5.4:7,c5.40:77,c5.43:5,c5.44:6,c5.45:6,c5.46:84,c5.47:11,c5.48:5,c5.49:52,c5.5:1,c5.50:59,c5.51:41,c5.52:75,c5.53:46,c5.54:25,c5.55:7,c5.56:13,c5.57:2,c5.58:2,c5.59:5,c5.6:31,c5.60:29,c5.61:54,c5.62:238,c5.7:15,c5.8:27,c5.9:24,c6.1:4,c6.2:4,c6.4:13,c6.5:1,c6.6:1,c7.1:26,c7.2:15,c8.1:4,c8.12:1,c8.13:7,c8.14:1,c8.16:1,c8.17:8,c8.2:9,c8.21:2,c8.23:13,c8.24:2,c8.26:1,c8.27:1,c8.3:1,c8.35:2,c8.36:4,c8.37:11,c8.38:6,c8.39:1,c8.4:20,c8.42:23,c8.43:13,c8.6:1,c8.8:1,c9.1:21,c9.10:7,c9.100:1,c9.1000:1,c9.1010:2,c9.1011:3,c9.1014:6,c9.1018:3,c9.1021:2,c9.1023:1,c9.1025:1,c9.1029:3,c9.1030:6,c9.1038:1,c9.1039:1,c9.1041:3,c9.106:1,c9.107:3,c9.109:5,c9.11:4,c9.110:1,c9.111:5,c9.112:1,c9.113:1,c9.115:1,c9.116:2,c9.117:2,c9.118:2,c9.12:3,c9.122:5,c9.123:2,c9.124:1,c9.125:4,c9.128:29,c9.129:1,c9.13:1,c9.130:4,c9.131:2,c9.138:2,c9.143:3,c9.145:1,c9.148:1,c9.149:1,c9.15:3,c9.155:3,c9.157:1,c9.158:14,c9.160:1,c9.161:1,c9.162:7,c9.163:3,c9.165:3,c9.166:2,c9.167:1,c9.169:4,c9.175:1,c9.176:2,c9.177:6,c9.178:3,c9.18:4,c9.180:1,c9.182:1,c9.183:1,c9.184:9,c9.187:1,c9.188:4,c9.189:1,c9.191:2,c9.192:2,c9.193:1,c9.195:3,c9.196:6,c9.198:4,c9.2:3,c9.200:1,c9.201:1,c9.202:3,c9.205:1,c9.206:1,c9.208:3,c9.209:2,c9.210:1,c9.212:3,c9.214:2,c9.215:8,c9.216:1,c9.219:2,c9.223:6,c9.224:4,c9.23:2,c9.230:2,c9.233:1,c9.235:4,c9.237:1,c9.238:1,c9.24:1,c9.244:1,c9.245:4,c9.249:1,c9.25:4,c9.253:1,c9.258:2,c9.259:2,c9.260:3,c9.263:2,c9.265:1,c9.266:1,c9.270:1,c9.274:1,c9.276:3,c9.277:1,c9.279:1,c9.28:3,c9.280:1,c9.282:4,c9.284:1,c9.285:2,c9.286:2,c9.287:1,c9.288:2,c9.289:2,c9.29:1,c9.290:1,c9.291:2,c9.293:4,c9.299:1,c9.3:21,c9.300:3,c9.302:4,c9.303:1,c9.304:1,c9.305:1,c9.307:3,c9.310:1,c9.314:2,c9.318:1,c9.32:1,c9.322:2,c9.328:1,c9.33:5,c9.330:1,c9.334:1,c9.338:1,c9.339:1,c9.34:7,c9.341:1,c9.35:2,c9.352:1,c9.354:4,c9.36:4,c9.371:1,c9.372:6,c9.373:2,c9.375:1,c9.378:7,c9.383:2,c9.384:13,c9.389:1,c9.39:10,c9.390:1,c9.394:2,c9.396:1,c9.398:1,c9.4:2,c9.40:1,c9.400:1,c9.401:1,c9.409:2,c9.415:2,c9.42:3,c9.422:1,c9.423:1,c9.424:1,c9.426:1,c9.427:1,c9.428:1,c9.437:1,c9.44:6,c9.440:4,c9.446:2,c9.447:1,c9.45:1,c9.46:5,c9.466:2,c9.467:3,c9.468:1,c9.469:1,c9.47:2,c9.470:1,c9.471:1,c9.472:1,c9.473:1,c9.474:2,c9.476:2,c9.477:2,c9.478:1,c9.479:8,c9.48:9,c9.480:10,c9.489:3,c9.49:1,c9.491:1,c9.492:1,c9.494:2,c9.496:1,c9.497:4,c9.498:10,c9.501:2,c9.502:2,c9.507:1,c9.511:16,c9.513:6,c9.517:1,c9.518:2,c9.519:4,c9.521:5,c9.522:14,c9.523:2,c9.528:2,c9.53:2,c9.536:1,c9.537:3,c9.539:5,c9.54:3,c9.545:1,c9.546:2,c9.547:1,c9.548:1,c9.549:1,c9.55:4,c9.550:1,c9.551:6,c9.552:1,c9.554:4,c9.556:2,c9.557:5,c9.559:2,c9.56:5,c9.560:5,c9.561:5,c9.562:1,c9.564:4,c9.565:1,c9.570:1,c9.574:2,c9.575:2,c9.576:2,c9.578:1,c9.579:23,c9.581:2,c9.585:1,c9.587:1,c9.588:2,c9.589:3,c9.590:2,c9.592:1,c9.594:1,c9.597:2,c9.599:2,c9.601:1,c9.606:1,c9.607:1,c9.613:2,c9.616:1,c9.618:2,c9.619:1,c9.62:2,c9.620:4,c9.621:1,c9.624:2,c9.625:3,c9.627:5,c9.629:4,c9.631:1,c9.632:5,c9.635:4,c9.640:4,c9.642:15,c9.643:1,c9.646:2,c9.648:10,c9.649:2,c9.650:3,c9.651:1,c9.652:1,c9.653:23,c9.654:2,c9.655:3,c9.658:5,c9.659:3,c9.66:5,c9.660:6,c9.661:3,c9.664:1,c9.666:1,c9.668:6,c9.669:8,c9.67:2,c9.670:6,c9.671:4,c9.672:1,c9.673:1,c9.674:2,c9.675:1,c9.676:2,c9.677:2,c9.678:1,c9.679:1,c9.68:2,c9.681:1,c9.683:3,c9.684:1,c9.686:1,c9.687:3,c9.688:1,c9.690:1,c9.692:3,c9.693:2,c9.696:1,c9.698:4,c9.700:2,c9.701:10,c9.702:2,c9.704:7,c9.705:1,c9.708:2,c9.71:5,c9.716:4,c9.718:1,c9.720:3,c9.721:1,c9.722:12,c9.723:9,c9.724:6,c9.726:24,c9.727:4,c9.73:1,c9.730:22,c9.731:1,c9.732:2,c9.734:1,c9.735:5,c9.736:6,c9.74:2,c9.740:1,c9.741:7,c9.742:1,c9.743:2,c9.744:2,c9.745:2,c9.746:4,c9.747:2,c9.748:13,c9.75:2,c9.750:3,c9.751:1,c9.752:2,c9.754:1,c9.757:3,c9.759:4,c9.76:5,c9.760:4,c9.761:1,c9.762:20,c9.763:1,c9.765:1,c9.766:10,c9.767:29,c9.770:1,c9.771:1,c9.775:10,c9.776:1,c9.778:1,c9.779:1,c9.782:1,c9.785:1,c9.786:1,c9.788:1,c9.789:2,c9.790:4,c9.792:5,c9.795:2,c9.8:3,c9.800:1,c9.802:4,c9.803:3,c9.806:2,c9.807:1,c9.808:1,c9.812:2,c9.814:1,c9.815:4,c9.816:4,c9.817:2,c9.82:2,c9.821:1,c9.825:1,c9.826:4,c9.829:1,c9.83:14,c9.831:4,c9.832:1,c9.833:1,c9.834:3,c9.838:2,c9.839:1,c9.840:1,c9.844:1,c9.845:1,c9.846:2,c9.848:1,c9.853:4,c9.857:1,c9.86:4,c9.860:8,c9.861:3,c9.862:2,c9.863:1,c9.864:22,c9.865:3,c9.867:3,c9.868:21,c9.870:1,c9.874:1,c9.877:3,c9.879:1,c9.88:2,c9.880:1,c9.882:1,c9.883:1,c9.884:7,c9.889:1,c9.89:1,c9.890:1,c9.897:2,c9.898:2,c9.899:2,c9.90:6,c9.900:2,c9.901:1,c9.903:8,c9.904:1,c9.908:2,c9.911:5,c9.912:1,c9.915:1,c9.916:1,c9.918:1,c9.920:1,c9.923:4,c9.926:7,c9.928:2,c9.930:3,c9.932:3,c9.933:3,c9.935:17,c9.940:1,c9.942:1,c9.946:1,c9.947:4,c9.948:2,c9.95:1,c9.955:6,c9.96:6,c9.962:1,c9.964:2,c9.965:2,c9.966:2,c9.970:1,c9.972:15,c9.973:4,c9.974:3,c9.975:3,c9.978:7,c9.98:1,c9.980:2,c9.984:1,c9.985:3,c9.986:3,c9.987:2,c9.988:1,c9.99:2,c9.992:1,c9.995:1,c9.997:1,v10.1:0.26799872704128,v10.2:0.294843030900723,v11.1:0.0311937606837607,v19.1:5.30864864864865,v19.2:5.59783783783784,v19.3:4.87081081081081,v19.4:5.43972972972973,v19.5:5.47324324324324,v19.6:5.15756756756757,v19.7:5.19135135135135,v19.8:5.74486486486486,v19.9:4.58486486486486,v20.10:-0.6355,v20.11:0.609416666666667,v20.12:-0.6084,v20.13:0.43653125,v20.14:-0.459692307692308,v20.15:0.377186046511628,v20.16:-0.401444444444444,v20.2:-0.396,v20.3:0.375,v20.4:-0.396,v20.5:0.75,v20.6:-0.597333333333333,v20.7:0.75,v20.8:-0.6355,v20.9:0.687571428571429,v21.1:5.29779697624191,v26.1:0.131034482758621					235|32||like the Americans hanged Saddam#1418|41||Yes but do you want to end up like Bush?#3462|77||When someone had to leave for Moscow or Tbilisi , who defended human rights?	Vladimir Putin,17;Georgian President Saakashvili,72;Getty Images,131;President Saakashvili,198;Vladimir Putin,367;Russian Prime Minister,508;David Levitte,657;Saddam Hussein,1328;French President,2543;South Ossetia,2803;Adolf Hitler,2967;United States,3579;Political Courage Prize,3821	30,miles,715;2,Russian leaders,2548;		<PAGE_AUTHORS>Infinite;</PAGE_AUTHORS><PAGE_PRECISEPUBTIMESTAMP>20081115085900</PAGE_PRECISEPUBTIMESTAMP>


In [13]:
import sys
!{sys.executable} -m pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\mgmorenogonz\AppData\Local\anaconda3\envs\deeplearning\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\mgmorenogonz\AppData\Local\anaconda3\envs\deeplearning\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 383.2 kB/s eta 0:00:25
   -- ------------------------------------- 0.5/9.7 MB 383.2 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.7 MB 455.8 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.7 MB 455.8 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.7 MB 455.8 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.7 MB 426.0 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.7 MB 426.0 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.7 MB 426.0 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 439.9 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.7 MB 439.9 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.7 MB 439.9 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.7 MB 410.6 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.7 MB 410.6 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.7 MB 410.6 kB/s eta 0:00:20
   ------- -------------------------------- 1.8/9.7 MB 425.4 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.7 MB 425.4 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.7 MB 425.4 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.7 MB 425.4 kB/s eta 0:00:19
   -------- ------------------------------- 2.1/9.7 MB 401.8 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.7 MB 401.8 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.7 MB 401.8 kB/s eta 0:00:20
   --------- ------------------------------ 2.4/9.7 MB 396.1 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.7 MB 396.1 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.7 MB 396.1 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.7 MB 396.1 kB/s eta 0:00:19
   ---------- ----------------------------- 2.6/9.7 MB 385.8 kB/s eta 0:00:19
   ---------- ----------------------------- 2.6/9.7 MB 385.8 kB/s eta 0:00:19
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.7 MB 394.3 kB/s eta 0:00:18
   ------------ --------------------------- 3.1/9.7 MB 368.6 kB/s eta 0:00:18
   ------------ --------------------------- 3.1/9.7 MB 368.6 kB/s eta 0:00:18
   ------------ --------------------------- 3.1/9.7 MB 368.6 kB/s eta 0:00:18
   ------------ --------------------------- 3.1/9.7 MB 368.6 kB/s eta 0:00:18
   ------------- -------------------------- 3.4/9.7 MB 364.4 kB/s eta 0:00:18
   ------------- -------------------------- 3.4/9.7 MB 364.4 kB/s eta 0:00:18
   --------------- ------------------------ 3.7/9.7 MB 373.3 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.7 MB 373.3 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.7 MB 373.3 kB/s eta 0:00:17
   ---------------- ----------------------- 3.9/9.7 MB 378.9 kB/s eta 0:00:16
   ---------------- ----------------------- 3.9/9.7 MB 378.9 kB/s eta 0:00:16
   ----------------- ---------------------- 4.2/9.7 MB 389.2 kB/s eta 0:00:15
   ----------------- ---------------------- 4.2/9.7 MB 389.2 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.7 MB 397.1 kB/s eta 0:00:14
   ------------------ --------------------- 4.5/9.7 MB 397.1 kB/s eta 0:00:14
   ------------------- -------------------- 4.7/9.7 MB 406.0 kB/s eta 0:00:13
   ------------------- -------------------- 4.7/9.7 MB 406.0 kB/s eta 0:00:13
   -------------------- ------------------- 5.0/9.7 MB 410.6 kB/s eta 0:00:12
   -------------------- ------------------- 5.0/9.7 MB 410.6 kB/s eta 0:00:12
   --------------------- ------------------ 5.2/9.7 MB 417.1 kB/s eta 0:00:11
   ---------------------- ----------------- 5.5/9.7 MB 429.3 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.7 MB 429.3 kB/s eta 0:00:10
   ----------------------- ---------------- 5.8/9.7 MB 436.5 kB/s eta 0:00:10
   ----------------------- ---------------- 5.8/9.7 MB 436.5 kB/s eta 0:00:10
   ------------------------ --------------- 6.0/9.7 MB 446.9 kB/s eta 0:00:09
   ------------------------- -------------- 6.3/9.7 MB 455.9 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 455.9 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 463.0 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 472.2 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 472.2 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 472.2 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 472.2 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 464.9 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.7 MB 464.9 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 469.6 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 469.6 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.7 MB 474.0 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 474.0 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 478.4 kB/s eta 0:00:04
   -------------------------------- ------- 7.9/9.7 MB 478.4 kB/s eta 0:00:04
   --------------------------------- ------ 8.1/9.7 MB 482.4 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 487.6 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.7 MB 487.6 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.7 MB 487.6 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 488.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 488.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 492.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 492.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 494.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 494.3 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.7 MB 496.6 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 496.6 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 499.1 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 497.5 kB/s  0:00:19
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 578.8 kB/s eta 0:00:21
   - -------------------------------------- 0.5/12.3 MB 578.8 kB/s eta 0:00:21
   - -------------------------------------- 0.5/12.3 MB 578.8 kB/s eta 0:00:21
   -- ------------------------------------- 0.8/12.3 MB 537.1 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/12.3 MB 537.1 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/12.3 MB 525.4 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/12.3 MB 525.4 kB/s eta 0:00:22
   ---- ----------------------------------- 1.3/12.3 MB 555.3 kB/s eta 0:00:20
   ---- ----------------------------------- 1.3/12.3 MB 555.3 kB/s eta 0:00:20
   ----- ---------------------------------- 1.6/12.3 MB 582.1 kB/s eta 0:00:19
   ----- ---------------------------------- 1.6/12.3 MB 582.1 kB/s eta 0:00:19
   ----- ---------------------------------- 1.8/12.3 MB 582.6 kB/s eta 0:00:18
   ----- ---------------------------------- 1.8/12.3 MB 582.6 kB/s eta 0:00:18
   ------ --------------------------------- 2.1/12.3 MB 579.0 kB/s eta 0:00:18
   ------ --------------------------------- 2.1/12.3 MB 579.0 kB/s eta 0:00:18
   ------- -------------------------------- 2.4/12.3 MB 572.4 kB/s eta 0:00:18
   ------- -------------------------------- 2.4/12.3 MB 572.4 kB/s eta 0:00:18
   ------- -------------------------------- 2.4/12.3 MB 572.4 kB/s eta 0:00:18
   ------- -------------------------------- 2.4/12.3 MB 572.4 kB/s eta 0:00:18
   -------- ------------------------------- 2.6/12.3 MB 544.0 kB/s eta 0:00:18
   -------- ------------------------------- 2.6/12.3 MB 544.0 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 540.4 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 540.4 kB/s eta 0:00:18
   ---------- ----------------------------- 3.1/12.3 MB 543.9 kB/s eta 0:00:17
   ---------- ----------------------------- 3.1/12.3 MB 543.9 kB/s eta 0:00:17
   ----------- ---------------------------- 3.4/12.3 MB 559.0 kB/s eta 0:00:16
   ----------- ---------------------------- 3.4/12.3 MB 559.0 kB/s eta 0:00:16
   ----------- ---------------------------- 3.7/12.3 MB 561.4 kB/s eta 0:00:16
   ----------- ---------------------------- 3.7/12.3 MB 561.4 kB/s eta 0:00:16
   ------------ --------------------------- 3.9/12.3 MB 556.6 kB/s eta 0:00:16
   ------------ --------------------------- 3.9/12.3 MB 556.6 kB/s eta 0:00:16
   ------------- -------------------------- 4.2/12.3 MB 562.0 kB/s eta 0:00:15
   ------------- -------------------------- 4.2/12.3 MB 562.0 kB/s eta 0:00:15
   -------------- ------------------------- 4.5/12.3 MB 570.7 kB/s eta 0:00:14
   --------------- ------------------------ 4.7/12.3 MB 579.7 kB/s eta 0:00:14
   --------------- ------------------------ 4.7/12.3 MB 579.7 kB/s eta 0:00:14
   ---------------- ----------------------- 5.0/12.3 MB 579.8 kB/s eta 0:00:13
   ---------------- ----------------------- 5.0/12.3 MB 579.8 kB/s eta 0:00:13
   ---------------- ----------------------- 5.0/12.3 MB 579.8 kB/s eta 0:00:13
   ----------------- ---------------------- 5.2/12.3 MB 578.4 kB/s eta 0:00:13
   ----------------- ---------------------- 5.2/12.3 MB 578.4 kB/s eta 0:00:13
   ----------------- ---------------------- 5.5/12.3 MB 573.0 kB/s eta 0:00:12
   ----------------- ---------------------- 5.5/12.3 MB 573.0 kB/s eta 0:00:12
   ------------------ --------------------- 5.8/12.3 MB 573.5 kB/s eta 0:00:12
   ------------------ --------------------- 5.8/12.3 MB 573.5 kB/s eta 0:00:12
   ------------------- -------------------- 6.0/12.3 MB 574.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.3 MB 574.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.3 MB 574.8 kB/s eta 0:00:11
   -------------------- ------------------- 6.3/12.3 MB 572.0 kB/s eta 0:00:11
   -------------------- ------------------- 6.3/12.3 MB 572.0 kB/s eta 0:00:11
   -------------------- ------------------- 6.3/12.3 MB 572.0 kB/s eta 0:00:11
   --------------------- ------------------ 6.6/12.3 MB 563.7 kB/s eta 0:00:11
   --------------------- ------------------ 6.6/12.3 MB 563.7 kB/s eta 0:00:11
   ---------------------- ----------------- 6.8/12.3 MB 559.6 kB/s eta 0:00:10
   ---------------------- ----------------- 6.8/12.3 MB 559.6 kB/s eta 0:00:10
   ---------------------- ----------------- 7.1/12.3 MB 568.6 kB/s eta 0:00:10
   ----------------------- ---------------- 7.3/12.3 MB 574.0 kB/s eta 0:00:09
   ----------------------- ---------------- 7.3/12.3 MB 574.0 kB/s eta 0:00:09
   ------------------------ --------------- 7.6/12.3 MB 575.1 kB/s eta 0:00:09
   ------------------------ --------------- 7.6/12.3 MB 575.1 kB/s eta 0:00:09
   ------------------------- -------------- 7.9/12.3 MB 575.2 kB/s eta 0:00:08
   ------------------------- -------------- 7.9/12.3 MB 575.2 kB/s eta 0:00:08
   ------------------------- -------------- 7.9/12.3 MB 575.2 kB/s eta 0:00:08
   -------------------------- ------------- 8.1/12.3 MB 573.7 kB/s eta 0:00:08
   --------------------------- ------------ 8.4/12.3 MB 578.5 kB/s eta 0:00:07
   --------------------------- ------------ 8.4/12.3 MB 578.5 kB/s eta 0:00:07
   --------------------------- ------------ 8.4/12.3 MB 578.5 kB/s eta 0:00:07
   ---------------------------- ----------- 8.7/12.3 MB 572.7 kB/s eta 0:00:07
   ---------------------------- ----------- 8.7/12.3 MB 572.7 kB/s eta 0:00:07
   ---------------------------- ----------- 8.9/12.3 MB 573.5 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.3 MB 573.5 kB/s eta 0:00:06
   ----------------------------- ---------- 9.2/12.3 MB 576.3 kB/s eta 0:00:06
   ------------------------------ --------- 9.4/12.3 MB 582.5 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.3 MB 582.5 kB/s eta 0:00:05
   ------------------------------- -------- 9.7/12.3 MB 587.4 kB/s eta 0:00:05
   -------------------------------- ------- 10.0/12.3 MB 592.7 kB/s eta 0:00:04
   -------------------------------- ------- 10.0/12.3 MB 592.7 kB/s eta 0:00:04
   -------------------------------- ------- 10.0/12.3 MB 592.7 kB/s eta 0:00:04
   --------------------------------- ------ 10.2/12.3 MB 586.8 kB/s eta 0:00:04
   --------------------------------- ------ 10.2/12.3 MB 586.8 kB/s eta 0:00:04
   ---------------------------------- ----- 10.5/12.3 MB 587.1 kB/s eta 0:00:04
   ---------------------------------- ----- 10.5/12.3 MB 587.1 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.3 MB 587.3 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.3 MB 587.3 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.3 MB 587.3 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.3 MB 587.3 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.3 MB 580.1 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.3 MB 580.1 kB/s eta 0:00:03
   ------------------------------------ --- 11.3/12.3 MB 578.8 kB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.3 MB 578.8 kB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.3 MB 578.8 kB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.3 MB 578.8 kB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.3 MB 568.1 kB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.3 MB 568.1 kB/s eta 0:00:02
   -------------------------------------- - 11.8/12.3 MB 564.7 kB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 564.7 kB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 564.7 kB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 564.7 kB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 564.7 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 553.8 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 553.8 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 553.8 kB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 553.8 kB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 544.3 kB/s  0:00:22
Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]

In [14]:
import pandas as pd

sample = pd.read_csv(
    zip_path,
    sep="\t",
    header=None,
    compression="zip",
    nrows=5
)

sample.iloc[:, :8]

,0,1,2,3,4,5,6,7
0,20171205211500-0,20171205211500,1,infiniteunknown.net,http://www.infiniteunknown.net/2008/11/15/vlad...,NaN,NaN,TAX_ETHNICITY;TAX_ETHNICITY_GEORGIAN;TAX_WORLD...
1,20171205211500-1,20171205211500,1,wickedlocal.com,http://lancaster.wickedlocal.com/news/20171205...,NaN,NaN,GEN_HOLIDAY;TAX_RELIGION;TAX_RELIGION_CONGREGA...
2,20171205211500-2,20171205211500,1,fox23.com,http://www.fox23.com/news/house-approves-legis...,NaN,NaN,LEGISLATION;USPEC_POLITICS_GENERAL1;USPEC_POLI...
3,20171205211500-3,20171205211500,1,kcbx.org,http://kcbx.org/?page=211,NaN,NaN,NATURAL_DISASTER;NATURAL_DISASTER_BRUSH_FIRE;N...
4,20171205211500-4,20171205211500,1,dnj.com,http://www.dnj.com/story/news/local/smyrna/bus...,NaN,NaN,EDUCATION;

In [15]:
colnames = [
    "gkg_record_id",
    "date",
    "source_collection_id",
    "source_common_name",
    "document_identifier",
    "v1_counts",
    "v2_counts",
    "v1_themes",
    "v2_enhanced_themes"
]

sample_small = sample.iloc[:, :9].copy()
sample_small.columns = colnames

sample_small[["date", "source_common_name", "document_identifier", "v1_themes"]]

,date,source_common_name,document_identifier,v1_themes
0,20171205211500,infiniteunknown.net,http://www.infiniteunknown.net/2008/11/15/vlad...,TAX_ETHNICITY;TAX_ETHNICITY_GEORGIAN;TAX_WORLD...
1,20171205211500,wickedlocal.com,http://lancaster.wickedlocal.com/news/20171205...,GEN_HOLIDAY;TAX_RELIGION;TAX_RELIGION_CONGREGA...
2,20171205211500,fox23.com,http://www.fox23.com/news/house-approves-legis...,LEGISLATION;USPEC_POLITICS_GENERAL1;USPEC_POLI...
3,20171205211500,kcbx.org,http://kcbx.org/?page=211,NATURAL_DISASTER;NATURAL_DISASTER_BRUSH_FIRE;N...
4,20171205211500,dnj.com,http://www.dnj.com/story/news/local/smyrna/bus...,EDUCATION;

In [16]:
sample_small["v1_themes_split"] = sample_small["v1_themes"].str.split(";")

sample_small[["source_common_name", "v1_themes_split"]]

    source_common_name                                    v1_themes_split
0  infiniteunknown.net  [TAX_ETHNICITY, TAX_ETHNICITY_GEORGIAN, TAX_WO...
1      wickedlocal.com  [GEN_HOLIDAY, TAX_RELIGION, TAX_RELIGION_CONGR...
2            fox23.com  [LEGISLATION, USPEC_POLITICS_GENERAL1, USPEC_P...
3             kcbx.org  [NATURAL_DISASTER, NATURAL_DISASTER_BRUSH_FIRE...
4              dnj.com                                      [EDUCATION, ]

In [17]:
sample.shape

(5, 27)

In [18]:
sample.iloc[:, 24:27]

,24,25,26
0,"30,miles,715;2,Russian leaders,2548;",NaN,<PAGE_AUTHORS>Infinite;</PAGE_AUTHORS><PAGE_PR...
1,"80,Main St,163;",NaN,<PAGE_AUTHORS>dimension3;</PAGE_AUTHORS><PAGE_...
2,NaN,NaN,<PAGE_LINKS>http://amp.fox23.com/news/house-ap...
3,"70,square miles near Santa,61;2,presidential t...",NaN,NaN
4,"427,Sam Ridley Parkway adjacent,215;150,restau...",NaN,<PAGE_LINKS>http://dnj.newspapers.com/?xid=123...

In [19]:
sample_small["extras_xml"] = sample.iloc[:, 26]

sample_small["page_precise_pubtimestamp"] = sample_small["extras_xml"].str.extract(
    r"<PAGE_PRECISEPUBTIMESTAMP>(\d+)</PAGE_PRECISEPUBTIMESTAMP>"
)

sample_small[["source_common_name", "date", "page_precise_pubtimestamp"]]

    source_common_name            date page_precise_pubtimestamp
0  infiniteunknown.net  20171205211500            20081115085900
1      wickedlocal.com  20171205211500            20171205135700
2            fox23.com  20171205211500            20171205204300
3             kcbx.org  20171205211500                       NaN
4              dnj.com  20171205211500            20171205195700

In [20]:
sample_small["has_precise_timestamp"] = sample_small["page_precise_pubtimestamp"].notna()

sample_small[["source_common_name", "has_precise_timestamp", "page_precise_pubtimestamp"]]

    source_common_name  has_precise_timestamp page_precise_pubtimestamp
0  infiniteunknown.net                   True            20081115085900
1      wickedlocal.com                   True            20171205135700
2            fox23.com                   True            20171205204300
3             kcbx.org                  False                       NaN
4              dnj.com                   True            20171205195700

In [21]:
sample_small["date_ymd"] = sample_small["date"].astype(str).str[:8]
sample_small["precise_ymd"] = sample_small["page_precise_pubtimestamp"].astype("string").str[:8]

sample_small["timestamp_mismatch"] = (
    sample_small["page_precise_pubtimestamp"].notna()
    & (sample_small["date_ymd"] != sample_small["precise_ymd"])
)

sample_small[[
    "source_common_name",
    "date_ymd",
    "precise_ymd",
    "timestamp_mismatch"
]]

    source_common_name  date_ymd precise_ymd  timestamp_mismatch
0  infiniteunknown.net  20171205    20081115                True
1      wickedlocal.com  20171205    20171205               False
2            fox23.com  20171205    20171205               False
3             kcbx.org  20171205        <NA>               False
4              dnj.com  20171205    20171205               False

In [23]:
sample_small["usable_timestamp"] = sample_small["page_precise_pubtimestamp"].astype("string")

mask = sample_small["page_precise_pubtimestamp"].isna() | sample_small["timestamp_mismatch"]

sample_small.loc[mask, "usable_timestamp"] = sample_small.loc[mask, "date"].astype("string")

sample_small[[
    "source_common_name",
    "date",
    "page_precise_pubtimestamp",
    "timestamp_mismatch",
    "usable_timestamp"
]]

,source_common_name,date,page_precise_pubtimestamp,timestamp_mismatch,usable_timestamp
0,infiniteunknown.net,20171205211500,20081115085900,True,20171205211500
1,wickedlocal.com,20171205211500,20171205135700,False,20171205135700
2,fox23.com,20171205211500,20171205204300,False,20171205204300
3,kcbx.org,20171205211500,NaN,False,20171205211500
4,dnj.com,20171205211500,20171205195700,False,20171205195700

In [24]:
from datetime import datetime, timedelta
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError

download_dir = RAW / "news"
download_dir.mkdir(parents=True, exist_ok=True)

# test first on ONE day
start = datetime(2017, 12, 5, 0, 0)
end   = datetime(2017, 12, 5, 23, 45)

def iter_15min(start_dt, end_dt):
    current = start_dt
    while current <= end_dt:
        yield current
        current += timedelta(minutes=15)

downloaded = 0
already_exists = 0
missing = 0
errors = 0

for ts in iter_15min(start, end):
    stamp = ts.strftime("%Y%m%d%H%M00")
    url = f"http://data.gdeltproject.org/gdeltv2/{stamp}.gkg.csv.zip"
    dest = download_dir / f"{stamp}.gkg.csv.zip"

    if dest.exists():
        already_exists += 1
        continue

    try:
        urlretrieve(url, dest)
        downloaded += 1
    except HTTPError as e:
        if e.code == 404:
            missing += 1
        else:
            errors += 1
            print(f"HTTP error {e.code} for {stamp}")
    except URLError as e:
        errors += 1
        print(f"URL error for {stamp}: {e}")

print("downloaded:", downloaded)
print("already_exists:", already_exists)
print("missing:", missing)
print("errors:", errors)

downloaded: 86
already_exists: 1
missing: 9
errors: 0

In [25]:
import pandas as pd
import re

news_folder = RAW / "news"
zip_files = sorted(news_folder.glob("20171205*.gkg.csv.zip"))

print("Number of zip files found:", len(zip_files))

frames = []

for zp in zip_files:
    try:
        df = pd.read_csv(
            zp,
            sep="\t",
            header=None,
            compression="zip",
            usecols=[0, 1, 3, 4, 7, 26],
            names=[
                "gkg_record_id",
                "date",
                "source_common_name",
                "document_identifier",
                "v1_themes",
                "extras_xml"
            ],
            dtype="string",
            on_bad_lines="skip"
        )

        df["page_precise_pubtimestamp"] = df["extras_xml"].str.extract(
            r"<PAGE_PRECISEPUBTIMESTAMP>(\d+)</PAGE_PRECISEPUBTIMESTAMP>"
        )

        df["date_ymd"] = df["date"].str[:8]
        df["precise_ymd"] = df["page_precise_pubtimestamp"].str[:8]

        df["timestamp_mismatch"] = (
            df["page_precise_pubtimestamp"].notna()
            & (df["date_ymd"] != df["precise_ymd"])
        )

        df["usable_timestamp"] = df["page_precise_pubtimestamp"]
        mask = df["page_precise_pubtimestamp"].isna() | df["timestamp_mismatch"]
        df.loc[mask, "usable_timestamp"] = df.loc[mask, "date"]

        frames.append(df)

    except Exception as e:
        print(f"Problem reading {zp.name}: {e}")

daily_gdelt = pd.concat(frames, ignore_index=True)

daily_gdelt = daily_gdelt[
    [
        "gkg_record_id",
        "date",
        "page_precise_pubtimestamp",
        "usable_timestamp",
        "timestamp_mismatch",
        "source_common_name",
        "document_identifier",
        "v1_themes",
    ]
]

print(daily_gdelt.shape)
daily_gdelt.head()

Number of zip files found: 87
(277067, 8)

,gkg_record_id,date,page_precise_pubtimestamp,usable_timestamp,timestamp_mismatch,source_common_name,document_identifier,v1_themes
0,20171205000000-0,20171205000000,20171204233700,20171205000000,True,theage.com.au,http://www.theage.com.au/afl/afl-news/immigrat...,<NA>
1,20171205000000-1,20171205000000,<NA>,20171205000000,False,philstar.com,http://m.philstar.com/782974/show/c05d63b160e8...,EDUCATION;
2,20171205000000-2,20171205000000,20171204222900,20171205000000,True,caledonianrecord.com,http://www.caledonianrecord.com/news/state/reg...,TAX_FNCACT;TAX_FNCACT_DIRECTORS;EDUCATION;SOC_...
3,20171205000000-3,20171205000000,20171204213000,20171205000000,True,sofrep.com,https://sofrep.com/95277/ar-build-tools-obsidi...,TAX_FNCACT;TAX_FNCACT_ARMORERS;CRISISLEX_CRISI...
4,20171205000000-4,20171205000000,<NA>,20171205000000,False,duke.fm,http://duke.fm/news/articles/2017/dec/04/liste...,MEDIA_MSM;NATURAL_DISASTER;NATURAL_DISASTER_HU...

In [26]:
daily_gdelt["timestamp_mismatch"].value_counts(dropna=False), daily_gdelt["page_precise_pubtimestamp"].notna().mean()

(timestamp_mismatch
 False    245428
 True      31639
 Name: count, dtype: Int64,
 np.float64(0.6071960933636991))

In [27]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [ ]:
from src.paths import RAW, PROCESSED
from gdelt_article_audit import build_gdelt_news_dataset

In [ ]:
daily_panel = build_gdelt_news_dataset(
    start_day="2017-12-01",
    end_day="2017-12-31",
    raw_news_dir=RAW / "news",
    processed_dir=PROCESSED,
    download_first=True,
    max_workers=12,
    save_article_level=True,
)

daily_panel.head()

=== 2017-12-01 ===
Download results: {'downloaded': 87, 'already_exists': 0, 'missing': 9, 'error': 0}
raw=264,681 | dedup=251,320 | relevant=223,709
Failed on 2017-12-01: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

=== 2017-12-02 ===
Download results: {'downloaded': 92, 'already_exists': 0, 'missing': 4, 'error': 0}
raw=163,483 | dedup=151,944 | relevant=132,542
Failed on 2017-12-02: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

=== 2017-12-03 ===
Download results: {'downloaded': 84, 'already_exists': 0, 'missing': 12, 'error': 0}
raw=125,099 | dedup=116,340 | relevant=101,286
Failed on 2017-12-03: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

=== 2017-12-04 ===
Download results: {'downloaded': 84, 'already_exists': 0, 'missing': 12, 'error': 0}
raw=234,416 | dedup=221,477 | relevant=196,338
Failed on 2017-12-04: No type extension with name arrow.py_extension_type found

=== 2017-12-05 ===
Download results: {'downloaded': 0, 'already_exists': 87, 'missing': 9, 'error': 0}
raw=277,067 | dedup=261,386 | relevant=231,467
Failed on 2017-12-05: A type extension with name pandas.period already defined

=== 2017-12-06 ===
Download results: {'downloaded': 88, 'already_exists': 0, 'missing': 8, 'error': 0}
raw=276,379 | dedup=261,537 | relevant=231,955
Failed on 2017-12-06: A type extension with name pandas.period already defined

=== 2017-12-07 ===
Download results: {'downloaded': 88, 'already_exists': 0, 'missing': 8, 'error': 0}
Problem reading 20171207154500.gkg.csv.zip: 'utf-8' codec can't decode byte 0x92 in position 18076: invalid start byte
raw=280,619 | dedup=265,200 | relevant=235,516
Failed on 2017-12-07: A type extension with name pandas.period already defined

=== 2017-12-08 ===
Download results: {'downloaded': 89, 'already_exists': 0, 'missing': 7, 'error': 0}
raw=267,906 | dedup=252,643 | relevant=224,190
Failed on 2017-12-08: A type extension with name pandas.period already defined

=== 2017-12-09 ===
Download results: {'downloaded': 87, 'already_exists': 0, 'missing': 9, 'error': 0}
Problem reading 20171209164500.gkg.csv.zip: 'utf-8' codec can't decode byte 0xa0 in position 6086: invalid start byte
raw=148,918 | dedup=138,267 | relevant=122,144
Failed on 2017-12-09: A type extension with name pandas.period already defined

=== 2017-12-10 ===
Download results: {'downloaded': 89, 'already_exists': 0, 'missing': 7, 'error': 0}
raw=129,369 | dedup=119,135 | relevant=104,959
Failed on 2017-12-10: A type extension with name pandas.period already defined

=== 2017-12-11 ===
Download results: {'downloaded': 82, 'already_exists': 0, 'missing': 14, 'error': 0}
raw=226,319 | dedup=213,578 | relevant=190,084
Failed on 2017-12-11: A type extension with name pandas.period already defined

=== 2017-12-12 ===
Download results: {'downloaded': 88, 'already_exists': 0, 'missing': 8, 'error': 0}
raw=263,424 | dedup=248,987 | relevant=223,099
Failed on 2017-12-12: A type extension with name pandas.period already defined

=== 2017-12-13 ===